dubbo:
  application:
    name: hmilydubboprovider-b
  registry:
    address: zookeeper://localhost:21810
  protocol:
    name: dubbo
    port: 20881
  scan:
    base-packages: hmilydubbo.impl
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:53306/mytest2?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      idle-timeout: 500000
      max-lifetime: 540000
      connection-timeout: 60000
      connection-test-query: SELECT 1
mybatis:
  mapper-locations: classpath:mapper/*.xml