server:
  port: 9528

dubbo:
  application:
    name: hmilydubboconsumer
  registry:
    address: zookeeper://localhost:21810
  protocol:
    name: dubbo
    port: 20880
  scan:
    base-packages: dubbohmily.service